// Objective-C API for talking to github.com/tzmax/apple-gotun2socks-library/tun2socks Go package.
//   gobind -lang=objc github.com/tzmax/apple-gotun2socks-library/tun2socks
//
// File is generated by gobind. Do not edit.

#ifndef __Tun2socks_H__
#define __Tun2socks_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class Tun2socksTun2socksCtl;
@protocol Tun2socksTunReadWriter;
@class Tun2socksTunReadWriter;

@protocol Tun2socksTunReadWriter <NSObject>
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
- (BOOL)read:(NSData* _Nullable)p0 n:(long* _Nullable)n error:(NSError* _Nullable* _Nullable)error;
- (BOOL)write:(NSData* _Nullable)p0 n:(long* _Nullable)n error:(NSError* _Nullable* _Nullable)error;
@end

@interface Tun2socksTun2socksCtl : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull tunName;
@end

FOUNDATION_EXPORT const int64_t Tun2socksMTU;

FOUNDATION_EXPORT Tun2socksTun2socksCtl* _Nullable Tun2socksConnect(id<Tun2socksTunReadWriter> _Nullable tunReadWriter, NSString* _Nullable socks5Proxy, BOOL isUDPEnabled, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT Tun2socksTun2socksCtl* _Nullable Tun2socksCreateTunConnect(NSString* _Nullable tunAddr, NSString* _Nullable tunWg, NSString* _Nullable tunMask, NSString* _Nullable tunDns, NSString* _Nullable socks5Proxy, BOOL isUDPEnabled, NSError* _Nullable* _Nullable error);

@class Tun2socksTunReadWriter;

@interface Tun2socksTunReadWriter : NSObject <goSeqRefInterface, Tun2socksTunReadWriter> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
- (BOOL)read:(NSData* _Nullable)p0 n:(long* _Nullable)n error:(NSError* _Nullable* _Nullable)error;
- (BOOL)write:(NSData* _Nullable)p0 n:(long* _Nullable)n error:(NSError* _Nullable* _Nullable)error;
@end

#endif
