
// Objective-C API for talking to the following Go packages
//
//	github.com/tzmax/apple-gotun2socks-library/tun2socks
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Tun2socks_FRAMEWORK_H__
#define __Tun2socks_FRAMEWORK_H__

#include "Tun2socks.objc.h"
#include "Universe.objc.h"

#endif
